name: Test MD Files

on:
  workflow_dispatch:
  workflow_call:
jobs:
  setup:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v4'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Build'
        run: pnpm build

      - name: 'Check Files for Non Markdown'
        run: 'node dist/scripts/checkFileExtensions.js'

      - name: 'Check for Markdown lint errors'
        run: 'node dist/scripts/checkErrors.js'

